FACEBOOK_ID: FACEBOOK_USER_NAME
FACEBOOK_PW: FACEBOOK_PASSWORD
GROUPS:
- GROUP_ID
- GROUP_ID
- GROUP_ID
- GROUP_ID
- GROUP_ID
- GROUP_ID
- GROUP_ID
- GROUP_ID
#you can use how many group_ids you want